name: LayeredyAnnounce
version: 1.1.0
main: services.plasma.layeredyannounce.LayeredyAnnouncePlugin
api-version: 1.20
authors:
  - Plasma Services
  - Layeredy Software
website: https://plasma.services
description: Layeredy Announce integration for Minecraft servers